// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecflowUnitTests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("SpecFlowTestsFeature", Description="\tSample Test Cases for the eAppriciation framework", SourceFile="SpecFlowTestFeature.feature", SourceLine=0)]
    public partial class SpecFlowTestsFeatureFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SpecFlowTestFeature.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SpecFlowTestsFeature", "\tSample Test Cases for the eAppriciation framework", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("SLIA-123: Verify that as a user, I should be able to add an appreciation without " +
            "a media file", new string[] {
                "mytag"}, SourceLine=9)]
        public virtual void SLIA_123VerifyThatAsAUserIShouldBeAbleToAddAnAppreciationWithoutAMediaFile()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("SLIA-123: Verify that as a user, I should be able to add an appreciation without " +
                    "a media file", new string[] {
                        "mytag"});
#line 10
 this.ScenarioSetup(scenarioInfo);
#line 12
 testRunner.Given("User is at eAppreciation Home Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 13
 testRunner.And("User has logged in with Spider credentials \'Mayuresh Ahirrao\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.When("I press add", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
 testRunner.Then("I land at the page \'The Wipfli Way - Add\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 17
 testRunner.And("My name \'Mayuresh Ahirrao\' is visible at the \'From\' textbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
 testRunner.When("I add name \'Bhushan Nalawade\' to the \'ToField\' textbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
 testRunner.And("I select given name from the \'ToField\' dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
 testRunner.Then("The given name \'Bhushan Nalawade\' is shown in \'To\' section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 23
 testRunner.When("I enter message \'This is a test message, generated automatically to test the Spec" +
                    "flow scripts.\' into the \'Message\' field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 24
 testRunner.But("no media file is selected", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "But ");
#line 25
 testRunner.Then("the message \'This is a test message, generated automatically to test the Specflow" +
                    " scripts.\' is added to the \'Message\' field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 27
 testRunner.When("I click on \'Save and Close\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 28
 testRunner.Then("I land at the page \'The Wipfli Way - View\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("SLIA-124: Verify that as a User, I can add multiple appreciations", SourceLine=29)]
        public virtual void SLIA_124VerifyThatAsAUserICanAddMultipleAppreciations()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("SLIA-124: Verify that as a User, I can add multiple appreciations", ((string[])(null)));
#line 30
this.ScenarioSetup(scenarioInfo);
#line 31
 testRunner.Given("User is at eAppreciation Home Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 32
 testRunner.And("User has logged in with Spider credentials \'Mayuresh Ahirrao\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
 testRunner.When("I press add", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 35
 testRunner.Then("I land at the page \'The Wipfli Way - Add\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 36
 testRunner.And("My name \'Mayuresh Ahirrao\' is visible at the \'From\' textbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
 testRunner.When("I add name \'Bhushan Nalawade\' to the \'ToField\' textbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 39
 testRunner.And("I select given name from the \'ToField\' dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
 testRunner.Then("The given name \'Bhushan Nalawade\' is shown in \'To\' section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 42
 testRunner.When("I enter message \'This is a test message, generated automatically to test the Spec" +
                    "flow scripts.\' into the \'Message\' field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 43
 testRunner.But("no media file is selected", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "But ");
#line 44
 testRunner.Then("the message \'This is a test message, generated automatically to test the Specflow" +
                    " scripts.\' is added to the \'Message\' field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 46
 testRunner.When("I click on \'Save and Add More\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 47
 testRunner.Then("I land at the page \'The Wipfli Way - Add\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 49
 testRunner.When("I add name \'Amit Agrawal\' to the \'ToField\' textbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 50
 testRunner.And("I select given name from the \'ToField\' dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
 testRunner.Then("The given name \'Amit Agrawal\' is shown in \'To\' section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 53
 testRunner.When("I enter message \'This is a test message, generated automatically to test the Spec" +
                    "flow scripts.\' into the \'Message\' field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 54
 testRunner.But("no media file is selected", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "But ");
#line 55
 testRunner.Then("the message \'This is a test message, generated automatically to test the Specflow" +
                    " scripts.\' is added to the \'Message\' field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 57
 testRunner.When("I click on \'Save and Close\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 58
 testRunner.Then("I land at the page \'The Wipfli Way - View\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("SLIA-125: Verify that as a user, I should be able to add an appreciation with a m" +
            "edia file.", SourceLine=59)]
        public virtual void SLIA_125VerifyThatAsAUserIShouldBeAbleToAddAnAppreciationWithAMediaFile_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("SLIA-125: Verify that as a user, I should be able to add an appreciation with a m" +
                    "edia file.", ((string[])(null)));
#line 60
this.ScenarioSetup(scenarioInfo);
#line 62
 testRunner.Given("User is at eAppreciation Home Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 63
 testRunner.And("User has logged in with Spider credentials \'Mayuresh Ahirrao\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 65
 testRunner.When("I press add", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 66
 testRunner.Then("I land at the page \'The Wipfli Way - Add\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 67
 testRunner.And("My name \'Mayuresh Ahirrao\' is visible at the \'From\' textbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 69
 testRunner.When("I add name \'Bhushan Nalawade\' to the \'ToField\' textbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 70
 testRunner.And("I select given name from the \'ToField\' dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 71
 testRunner.Then("The given name \'Bhushan Nalawade\' is shown in \'To\' section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 73
 testRunner.When("I enter message \'This is a test message, generated automatically to test the Spec" +
                    "flow scripts.\' into the \'Message\' field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 74
 testRunner.And("Media file \'D:\\Company Docs\\Webinars\\Scriptless Automation\\click button actions.j" +
                    "pg\' is selected", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 75
 testRunner.Then("the message \'This is a test message, generated automatically to test the Specflow" +
                    " scripts.\' is added to the \'Message\' field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 77
 testRunner.When("I click on \'Save and Close\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 78
 testRunner.Then("I land at the page \'The Wipfli Way - View\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
